/**
License:
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.

Authors:
	aermicioi
**/
module aermicioi.aedi.exception.di_exception;

import std.exception;
import aermicioi.aedi.util.range : BufferSink;

@safe:

/**
General type of exception thrown by library.

General type of exception thrown by library.
All kind of exceptions should inherit from this base one.
Used as well for general types of exceptions that do not fit in certain
category.
**/
class AediException : Exception {

    /**
    Identity of offending component.
    **/
    string identity;

    /**
     * Creates a new instance of Exception. The nextInChain parameter is used
     * internally and should always be $(D null) when passed by user code.
     * This constructor does not automatically throw the newly-created
     * Exception; the $(D throw) statement should be used for that purpose.
     */
    pure nothrow this(string msg, string identity, string file = __FILE__, size_t line = __LINE__, Throwable next = null)
    {
        this.identity = identity;
        super(msg, file, line, next);
    }

    /**
    ditto
    **/
    nothrow this(string msg, string identity, Throwable next, string file = __FILE__, size_t line = __LINE__)
    {
        this.identity = identity;
        super(msg, file, line, next);
    }

    mixin AdvancedExceptionPrinting;

    /**
    A special function used to print customized message using built-in properties, with as less as possible allocations.

    Params:
        sink = sink where message will end.
    **/
    void pushMessage(scope void delegate(in char[]) sink) const @system {
        import std.algorithm : substitute;
        import std.utf : byChar;
		auto substituted = this.msg.substitute("${identity}", identity).byChar;

        while (!substituted.empty) {
            auto buffer = BufferSink!(char[256])();
            buffer.put(substituted);

            sink(buffer.slice);
        }
    }

    alias toString = typeof(super).toString;
}

/**
A mixin injecting modified version of toString which uses pushMessage instead of msg.
**/
mixin template AdvancedExceptionPrinting() {
	override void toString(scope void delegate(in char[]) sink) const @system
    {
        import core.internal.string : unsignedToTempString;

        char[20] tmpBuff = void;

        sink(typeid(this).name);
        sink("@"); sink(file);
        sink("("); sink(unsignedToTempString(line, tmpBuff, 10)); sink(")");

        if (msg.length)
        {
            sink(": "); pushMessage(sink);
        }
        if (info)
        {
            try
            {
                sink("\n----------------");
                foreach (t; info)
                {
                    sink("\n"); sink(t);
                }
            }
            catch (Throwable)
            {
                // ignore more errors
            }
        }
    }
}